//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.05 at 05:54:01 PM SAST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ietf:params:xml:ns:reginfo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.smilecoms.mm.plugins.onnetsms.reginfo.ietf.params.xml.ns.reginfo;
