<?xml version="1.0" encoding="UTF-8"?>
<definitions name="BulkDeviceProvisioning" targetNamespace="http://xml.smilecoms.com/FileProcessing"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:file="http://schemas.sun.com/jbi/wsdl-extensions/file/" xmlns:tns="http://xml.smilecoms.com/FileProcessing">
    <types/>
    <message name="BulkProcessingLineRequest">
        <part name="FileLine" type="xsd:string"/>
    </message>
   
    <portType name="FileProcessing">
        <operation name="ProvisionDevice">
            <input name="input1" message="tns:BulkProcessingLineRequest"/>
        </operation>
    </portType>
    <binding name="FileProcessingBinding" type="tns:FileProcessing">
        <file:binding/>
        <operation name="ProvisionDevice">
            <file:operation/>
            <input name="input1">
                <file:message use="literal" fileName="device_provisioning_data_%t.txt" pollingInterval="10000" fileType="text" fileNameIsPattern="true" multipleRecordsPerFile="true" archive="true" archiveDirectory="../processed" archiveDirIsRelative="true" recordDelimiter="\r\n"/>
            </input>
        </operation>
    </binding>
    <service name="FileProcessing">
        <port name="FileProcessing" binding="tns:FileProcessingBinding">
            <file:address fileDirectory="/tmp/attachments" lockName="filebc.lck" workArea="filebc_tmp" seqName="filebc.seq" relativePath="false"/>
        </port>
    </service>
    <plnk:partnerLinkType name="BulkDeviceProvisioning">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="BulkDeviceProvisioningFileRole" portType="tns:FileProcessing"/>
    </plnk:partnerLinkType>
</definitions>
