package com.smilecoms.im.nimc.identitysearch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2021-01-12T07:29:21.946+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://IdentitySearch.nimc/", name = "IdentitySearch")
@XmlSeeAlso({ObjectFactory.class})
public interface IdentitySearch {

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByNINRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByNINResponse")
    @RequestWrapper(localName = "searchByNIN", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByNIN")
    @ResponseWrapper(localName = "searchByNINResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByNINResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.SearchResponseDemo searchByNIN(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "nin", targetNamespace = "")
        java.lang.String nin
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByFingerRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByFingerResponse")
    @RequestWrapper(localName = "searchByFinger", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByFinger")
    @ResponseWrapper(localName = "searchByFingerResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByFingerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.SearchResponseDemo searchByFinger(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "data", targetNamespace = "")
        java.lang.String data,
        @WebParam(name = "FingerPositionCode", targetNamespace = "")
        int fingerPositionCode
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getPermissionByLevelRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getPermissionByLevelResponse")
    @RequestWrapper(localName = "getPermissionByLevel", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.GetPermissionByLevel")
    @ResponseWrapper(localName = "getPermissionByLevelResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.GetPermissionByLevelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.DemoMapPermission getPermissionByLevel(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "level", targetNamespace = "")
        int level
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByDemoRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByDemoResponse")
    @RequestWrapper(localName = "searchByDemo", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByDemo")
    @ResponseWrapper(localName = "searchByDemoResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByDemoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.SearchResponseDemo searchByDemo(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "DemoDataMandatory", targetNamespace = "")
        com.smilecoms.im.nimc.identitysearch.DemoDataMandatory demoDataMandatory
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/updateUserSELFRequest", output = "http://IdentitySearch.nimc/IdentitySearch/updateUserSELFResponse")
    @RequestWrapper(localName = "updateUserSELF", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.UpdateUserSELF")
    @ResponseWrapper(localName = "updateUserSELFResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.UpdateUserSELFResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.LoginMessage updateUserSELF(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "nin", targetNamespace = "")
        java.lang.String nin,
        @WebParam(name = "surname", targetNamespace = "")
        java.lang.String surname,
        @WebParam(name = "firstname", targetNamespace = "")
        java.lang.String firstname,
        @WebParam(name = "phone", targetNamespace = "")
        java.lang.String phone,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/createTokenStringRequest", output = "http://IdentitySearch.nimc/IdentitySearch/createTokenStringResponse")
    @RequestWrapper(localName = "createTokenString", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.CreateTokenString")
    @ResponseWrapper(localName = "createTokenStringResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.CreateTokenStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String createTokenString(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "orgid", targetNamespace = "")
        java.lang.String orgid
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByPhotoRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByPhotoResponse")
    @RequestWrapper(localName = "searchByPhoto", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByPhoto")
    @ResponseWrapper(localName = "searchByPhotoResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByPhotoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.SearchResponseDemo searchByPhoto(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "data", targetNamespace = "")
        java.lang.String data
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByDemoPhoneRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByDemoPhoneResponse")
    @RequestWrapper(localName = "searchByDemoPhone", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByDemoPhone")
    @ResponseWrapper(localName = "searchByDemoPhoneResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByDemoPhoneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.SearchResponseDemo searchByDemoPhone(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "DemoDataMandatory", targetNamespace = "")
        java.lang.String demoDataMandatory
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByDocumentNumberRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByDocumentNumberResponse")
    @RequestWrapper(localName = "searchByDocumentNumber", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByDocumentNumber")
    @ResponseWrapper(localName = "searchByDocumentNumberResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.SearchByDocumentNumberResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.SearchResponseDemo searchByDocumentNumber(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "doc", targetNamespace = "")
        java.lang.String doc
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/verifyPhotoWithDataRequest", output = "http://IdentitySearch.nimc/IdentitySearch/verifyPhotoWithDataResponse")
    @RequestWrapper(localName = "verifyPhotoWithData", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.VerifyPhotoWithData")
    @ResponseWrapper(localName = "verifyPhotoWithDataResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.VerifyPhotoWithDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.SearchResponseDemo verifyPhotoWithData(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "nin", targetNamespace = "")
        java.lang.String nin,
        @WebParam(name = "photoStringInBase64", targetNamespace = "")
        java.lang.String photoStringInBase64,
        @WebParam(name = "pos", targetNamespace = "")
        int pos
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/verifyFingerWithDataRequest", output = "http://IdentitySearch.nimc/IdentitySearch/verifyFingerWithDataResponse")
    @RequestWrapper(localName = "verifyFingerWithData", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.VerifyFingerWithData")
    @ResponseWrapper(localName = "verifyFingerWithDataResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.VerifyFingerWithDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.SearchResponseDemo verifyFingerWithData(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "nin", targetNamespace = "")
        java.lang.String nin,
        @WebParam(name = "fingerStringInBase64", targetNamespace = "")
        java.lang.String fingerStringInBase64,
        @WebParam(name = "pos", targetNamespace = "")
        int pos
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/createTokenRequest", output = "http://IdentitySearch.nimc/IdentitySearch/createTokenResponse")
    @RequestWrapper(localName = "createToken", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.CreateToken")
    @ResponseWrapper(localName = "createTokenResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.CreateTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.TokenObject createToken(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "orgid", targetNamespace = "")
        java.lang.String orgid
    );

    @WebMethod
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/changePasswordRequest", output = "http://IdentitySearch.nimc/IdentitySearch/changePasswordResponse")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "nimc.identitysearch.ChangePasswordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.smilecoms.im.nimc.identitysearch.TokenObject changePassword(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "newpassword", targetNamespace = "")
        java.lang.String newpassword
    );
}
