<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="text" version="1.0" encoding="utf-8" omit-xml-declaration="yes" media-type="text/xml" indent="no" />
    <xsl:template match="/">
 
 
package com.smilecoms.commons.sca;

/*

NOTE: This class is auto-generated by a XSL run from with SCA-Client build.xml

ANY MANUAL EDITS WILL BE LOST!

*/

public class SCATypes extends AbstractSCATypes{
    
    <xsl:for-each select="//type[not(.=preceding::type)]">
        
    <xsl:text>private </xsl:text><xsl:value-of select="."/><xsl:text> </xsl:text><xsl:value-of select="."/>;
    
    <xsl:text>public </xsl:text><xsl:value-of select="."/><xsl:text> get</xsl:text><xsl:value-of select="."/>() {
        return <xsl:value-of select="."/>;
    }
    <xsl:text>public void </xsl:text><xsl:text>set</xsl:text><xsl:value-of select="."/>(<xsl:value-of select="."/><xsl:text> </xsl:text><xsl:value-of select="."/>) {
        this.<xsl:value-of select="."/>=<xsl:value-of select="."/>;
    }        
    </xsl:for-each>
        
} 
 
    </xsl:template>
</xsl:stylesheet>