
 
 
package com.smilecoms.commons.sca;

/*

NOTE: This class is auto-generated by a XSL run from with SCA-Client build.xml

ANY MANUAL EDITS WILL BE LOST!

*/

public class SCATypes extends AbstractSCATypes{
    
    private CCQueueLoginData CCQueueLoginData;
    
    public CCQueueLoginData getCCQueueLoginData() {
        return CCQueueLoginData;
    }
    public void setCCQueueLoginData(CCQueueLoginData CCQueueLoginData) {
        this.CCQueueLoginData=CCQueueLoginData;
    }        
    private Done Done;
    
    public Done getDone() {
        return Done;
    }
    public void setDone(Done Done) {
        this.Done=Done;
    }        
    private TTCommentQuery TTCommentQuery;
    
    public TTCommentQuery getTTCommentQuery() {
        return TTCommentQuery;
    }
    public void setTTCommentQuery(TTCommentQuery TTCommentQuery) {
        this.TTCommentQuery=TTCommentQuery;
    }        
    private TTCommentList TTCommentList;
    
    public TTCommentList getTTCommentList() {
        return TTCommentList;
    }
    public void setTTCommentList(TTCommentList TTCommentList) {
        this.TTCommentList=TTCommentList;
    }        
    private CreditNoteQuery CreditNoteQuery;
    
    public CreditNoteQuery getCreditNoteQuery() {
        return CreditNoteQuery;
    }
    public void setCreditNoteQuery(CreditNoteQuery CreditNoteQuery) {
        this.CreditNoteQuery=CreditNoteQuery;
    }        
    private CreditNoteList CreditNoteList;
    
    public CreditNoteList getCreditNoteList() {
        return CreditNoteList;
    }
    public void setCreditNoteList(CreditNoteList CreditNoteList) {
        this.CreditNoteList=CreditNoteList;
    }        
    private ProductInstanceQuery ProductInstanceQuery;
    
    public ProductInstanceQuery getProductInstanceQuery() {
        return ProductInstanceQuery;
    }
    public void setProductInstanceQuery(ProductInstanceQuery ProductInstanceQuery) {
        this.ProductInstanceQuery=ProductInstanceQuery;
    }        
    private ProductInstanceList ProductInstanceList;
    
    public ProductInstanceList getProductInstanceList() {
        return ProductInstanceList;
    }
    public void setProductInstanceList(ProductInstanceList ProductInstanceList) {
        this.ProductInstanceList=ProductInstanceList;
    }        
    private NewTTIssue NewTTIssue;
    
    public NewTTIssue getNewTTIssue() {
        return NewTTIssue;
    }
    public void setNewTTIssue(NewTTIssue NewTTIssue) {
        this.NewTTIssue=NewTTIssue;
    }        
    private TTIssue TTIssue;
    
    public TTIssue getTTIssue() {
        return TTIssue;
    }
    public void setTTIssue(TTIssue TTIssue) {
        this.TTIssue=TTIssue;
    }        
    private UpdatePropertyRequest UpdatePropertyRequest;
    
    public UpdatePropertyRequest getUpdatePropertyRequest() {
        return UpdatePropertyRequest;
    }
    public void setUpdatePropertyRequest(UpdatePropertyRequest UpdatePropertyRequest) {
        this.UpdatePropertyRequest=UpdatePropertyRequest;
    }        
    private Account Account;
    
    public Account getAccount() {
        return Account;
    }
    public void setAccount(Account Account) {
        this.Account=Account;
    }        
    private Sale Sale;
    
    public Sale getSale() {
        return Sale;
    }
    public void setSale(Sale Sale) {
        this.Sale=Sale;
    }        
    private CCAgentData CCAgentData;
    
    public CCAgentData getCCAgentData() {
        return CCAgentData;
    }
    public void setCCAgentData(CCAgentData CCAgentData) {
        this.CCAgentData=CCAgentData;
    }        
    private StickyNote StickyNote;
    
    public StickyNote getStickyNote() {
        return StickyNote;
    }
    public void setStickyNote(StickyNote StickyNote) {
        this.StickyNote=StickyNote;
    }        
    private BatchSchedule BatchSchedule;
    
    public BatchSchedule getBatchSchedule() {
        return BatchSchedule;
    }
    public void setBatchSchedule(BatchSchedule BatchSchedule) {
        this.BatchSchedule=BatchSchedule;
    }        
    private IncomingCCAgentCallData IncomingCCAgentCallData;
    
    public IncomingCCAgentCallData getIncomingCCAgentCallData() {
        return IncomingCCAgentCallData;
    }
    public void setIncomingCCAgentCallData(IncomingCCAgentCallData IncomingCCAgentCallData) {
        this.IncomingCCAgentCallData=IncomingCCAgentCallData;
    }        
    private PromotionCodeApprovalData PromotionCodeApprovalData;
    
    public PromotionCodeApprovalData getPromotionCodeApprovalData() {
        return PromotionCodeApprovalData;
    }
    public void setPromotionCodeApprovalData(PromotionCodeApprovalData PromotionCodeApprovalData) {
        this.PromotionCodeApprovalData=PromotionCodeApprovalData;
    }        
    private ReservationRequestData ReservationRequestData;
    
    public ReservationRequestData getReservationRequestData() {
        return ReservationRequestData;
    }
    public void setReservationRequestData(ReservationRequestData ReservationRequestData) {
        this.ReservationRequestData=ReservationRequestData;
    }        
    private ReservationResultData ReservationResultData;
    
    public ReservationResultData getReservationResultData() {
        return ReservationResultData;
    }
    public void setReservationResultData(ReservationResultData ReservationResultData) {
        this.ReservationResultData=ReservationResultData;
    }        
    private Contract Contract;
    
    public Contract getContract() {
        return Contract;
    }
    public void setContract(Contract Contract) {
        this.Contract=Contract;
    }        
    private SCAInteger SCAInteger;
    
    public SCAInteger getSCAInteger() {
        return SCAInteger;
    }
    public void setSCAInteger(SCAInteger SCAInteger) {
        this.SCAInteger=SCAInteger;
    }        
    private Organisation Organisation;
    
    public Organisation getOrganisation() {
        return Organisation;
    }
    public void setOrganisation(Organisation Organisation) {
        this.Organisation=Organisation;
    }        
    private PropertyRequest PropertyRequest;
    
    public PropertyRequest getPropertyRequest() {
        return PropertyRequest;
    }
    public void setPropertyRequest(PropertyRequest PropertyRequest) {
        this.PropertyRequest=PropertyRequest;
    }        
    private PropertyResponse PropertyResponse;
    
    public PropertyResponse getPropertyResponse() {
        return PropertyResponse;
    }
    public void setPropertyResponse(PropertyResponse PropertyResponse) {
        this.PropertyResponse=PropertyResponse;
    }        
    private SplitUnitCreditData SplitUnitCreditData;
    
    public SplitUnitCreditData getSplitUnitCreditData() {
        return SplitUnitCreditData;
    }
    public void setSplitUnitCreditData(SplitUnitCreditData SplitUnitCreditData) {
        this.SplitUnitCreditData=SplitUnitCreditData;
    }        
    private Customer Customer;
    
    public Customer getCustomer() {
        return Customer;
    }
    public void setCustomer(Customer Customer) {
        this.Customer=Customer;
    }        
    private IMSSubscriptionQuery IMSSubscriptionQuery;
    
    public IMSSubscriptionQuery getIMSSubscriptionQuery() {
        return IMSSubscriptionQuery;
    }
    public void setIMSSubscriptionQuery(IMSSubscriptionQuery IMSSubscriptionQuery) {
        this.IMSSubscriptionQuery=IMSSubscriptionQuery;
    }        
    private IMSSubscription IMSSubscription;
    
    public IMSSubscription getIMSSubscription() {
        return IMSSubscription;
    }
    public void setIMSSubscription(IMSSubscription IMSSubscription) {
        this.IMSSubscription=IMSSubscription;
    }        
    private FlushPropertyCacheRequest FlushPropertyCacheRequest;
    
    public FlushPropertyCacheRequest getFlushPropertyCacheRequest() {
        return FlushPropertyCacheRequest;
    }
    public void setFlushPropertyCacheRequest(FlushPropertyCacheRequest FlushPropertyCacheRequest) {
        this.FlushPropertyCacheRequest=FlushPropertyCacheRequest;
    }        
    private UnitCreditSpecificationQuery UnitCreditSpecificationQuery;
    
    public UnitCreditSpecificationQuery getUnitCreditSpecificationQuery() {
        return UnitCreditSpecificationQuery;
    }
    public void setUnitCreditSpecificationQuery(UnitCreditSpecificationQuery UnitCreditSpecificationQuery) {
        this.UnitCreditSpecificationQuery=UnitCreditSpecificationQuery;
    }        
    private UnitCreditSpecificationList UnitCreditSpecificationList;
    
    public UnitCreditSpecificationList getUnitCreditSpecificationList() {
        return UnitCreditSpecificationList;
    }
    public void setUnitCreditSpecificationList(UnitCreditSpecificationList UnitCreditSpecificationList) {
        this.UnitCreditSpecificationList=UnitCreditSpecificationList;
    }        
    private CustomerQueryOtherMNORequest CustomerQueryOtherMNORequest;
    
    public CustomerQueryOtherMNORequest getCustomerQueryOtherMNORequest() {
        return CustomerQueryOtherMNORequest;
    }
    public void setCustomerQueryOtherMNORequest(CustomerQueryOtherMNORequest CustomerQueryOtherMNORequest) {
        this.CustomerQueryOtherMNORequest=CustomerQueryOtherMNORequest;
    }        
    private CustomerQueryOtherMNOResponse CustomerQueryOtherMNOResponse;
    
    public CustomerQueryOtherMNOResponse getCustomerQueryOtherMNOResponse() {
        return CustomerQueryOtherMNOResponse;
    }
    public void setCustomerQueryOtherMNOResponse(CustomerQueryOtherMNOResponse CustomerQueryOtherMNOResponse) {
        this.CustomerQueryOtherMNOResponse=CustomerQueryOtherMNOResponse;
    }        
    private InventoryQuery InventoryQuery;
    
    public InventoryQuery getInventoryQuery() {
        return InventoryQuery;
    }
    public void setInventoryQuery(InventoryQuery InventoryQuery) {
        this.InventoryQuery=InventoryQuery;
    }        
    private InventoryList InventoryList;
    
    public InventoryList getInventoryList() {
        return InventoryList;
    }
    public void setInventoryList(InventoryList InventoryList) {
        this.InventoryList=InventoryList;
    }        
    private IMEIStatusChangeRequest IMEIStatusChangeRequest;
    
    public IMEIStatusChangeRequest getIMEIStatusChangeRequest() {
        return IMEIStatusChangeRequest;
    }
    public void setIMEIStatusChangeRequest(IMEIStatusChangeRequest IMEIStatusChangeRequest) {
        this.IMEIStatusChangeRequest=IMEIStatusChangeRequest;
    }        
    private TTCloseSalesLeadIssueQuery TTCloseSalesLeadIssueQuery;
    
    public TTCloseSalesLeadIssueQuery getTTCloseSalesLeadIssueQuery() {
        return TTCloseSalesLeadIssueQuery;
    }
    public void setTTCloseSalesLeadIssueQuery(TTCloseSalesLeadIssueQuery TTCloseSalesLeadIssueQuery) {
        this.TTCloseSalesLeadIssueQuery=TTCloseSalesLeadIssueQuery;
    }        
    private Address Address;
    
    public Address getAddress() {
        return Address;
    }
    public void setAddress(Address Address) {
        this.Address=Address;
    }        
    private StickyNoteEntityIdentifier StickyNoteEntityIdentifier;
    
    public StickyNoteEntityIdentifier getStickyNoteEntityIdentifier() {
        return StickyNoteEntityIdentifier;
    }
    public void setStickyNoteEntityIdentifier(StickyNoteEntityIdentifier StickyNoteEntityIdentifier) {
        this.StickyNoteEntityIdentifier=StickyNoteEntityIdentifier;
    }        
    private StickyNoteList StickyNoteList;
    
    public StickyNoteList getStickyNoteList() {
        return StickyNoteList;
    }
    public void setStickyNoteList(StickyNoteList StickyNoteList) {
        this.StickyNoteList=StickyNoteList;
    }        
    private PCRFDataQuery PCRFDataQuery;
    
    public PCRFDataQuery getPCRFDataQuery() {
        return PCRFDataQuery;
    }
    public void setPCRFDataQuery(PCRFDataQuery PCRFDataQuery) {
        this.PCRFDataQuery=PCRFDataQuery;
    }        
    private PCRFData PCRFData;
    
    public PCRFData getPCRFData() {
        return PCRFData;
    }
    public void setPCRFData(PCRFData PCRFData) {
        this.PCRFData=PCRFData;
    }        
    private CashInQuery CashInQuery;
    
    public CashInQuery getCashInQuery() {
        return CashInQuery;
    }
    public void setCashInQuery(CashInQuery CashInQuery) {
        this.CashInQuery=CashInQuery;
    }        
    private CashInList CashInList;
    
    public CashInList getCashInList() {
        return CashInList;
    }
    public void setCashInList(CashInList CashInList) {
        this.CashInList=CashInList;
    }        
    private PortOrdersQuery PortOrdersQuery;
    
    public PortOrdersQuery getPortOrdersQuery() {
        return PortOrdersQuery;
    }
    public void setPortOrdersQuery(PortOrdersQuery PortOrdersQuery) {
        this.PortOrdersQuery=PortOrdersQuery;
    }        
    private PortOrdersList PortOrdersList;
    
    public PortOrdersList getPortOrdersList() {
        return PortOrdersList;
    }
    public void setPortOrdersList(PortOrdersList PortOrdersList) {
        this.PortOrdersList=PortOrdersList;
    }        
    private SSOPasswordResetLinkData SSOPasswordResetLinkData;
    
    public SSOPasswordResetLinkData getSSOPasswordResetLinkData() {
        return SSOPasswordResetLinkData;
    }
    public void setSSOPasswordResetLinkData(SSOPasswordResetLinkData SSOPasswordResetLinkData) {
        this.SSOPasswordResetLinkData=SSOPasswordResetLinkData;
    }        
    private SSOPasswordResetLink SSOPasswordResetLink;
    
    public SSOPasswordResetLink getSSOPasswordResetLink() {
        return SSOPasswordResetLink;
    }
    public void setSSOPasswordResetLink(SSOPasswordResetLink SSOPasswordResetLink) {
        this.SSOPasswordResetLink=SSOPasswordResetLink;
    }        
    private RatePlan RatePlan;
    
    public RatePlan getRatePlan() {
        return RatePlan;
    }
    public void setRatePlan(RatePlan RatePlan) {
        this.RatePlan=RatePlan;
    }        
    private TenantQuery TenantQuery;
    
    public TenantQuery getTenantQuery() {
        return TenantQuery;
    }
    public void setTenantQuery(TenantQuery TenantQuery) {
        this.TenantQuery=TenantQuery;
    }        
    private TenantData TenantData;
    
    public TenantData getTenantData() {
        return TenantData;
    }
    public void setTenantData(TenantData TenantData) {
        this.TenantData=TenantData;
    }        
    private UnitCreditInstanceQuery UnitCreditInstanceQuery;
    
    public UnitCreditInstanceQuery getUnitCreditInstanceQuery() {
        return UnitCreditInstanceQuery;
    }
    public void setUnitCreditInstanceQuery(UnitCreditInstanceQuery UnitCreditInstanceQuery) {
        this.UnitCreditInstanceQuery=UnitCreditInstanceQuery;
    }        
    private UnitCreditInstanceList UnitCreditInstanceList;
    
    public UnitCreditInstanceList getUnitCreditInstanceList() {
        return UnitCreditInstanceList;
    }
    public void setUnitCreditInstanceList(UnitCreditInstanceList UnitCreditInstanceList) {
        this.UnitCreditInstanceList=UnitCreditInstanceList;
    }        
    private PrepaidStripBatchData PrepaidStripBatchData;
    
    public PrepaidStripBatchData getPrepaidStripBatchData() {
        return PrepaidStripBatchData;
    }
    public void setPrepaidStripBatchData(PrepaidStripBatchData PrepaidStripBatchData) {
        this.PrepaidStripBatchData=PrepaidStripBatchData;
    }        
    private AccountHistoryQuery AccountHistoryQuery;
    
    public AccountHistoryQuery getAccountHistoryQuery() {
        return AccountHistoryQuery;
    }
    public void setAccountHistoryQuery(AccountHistoryQuery AccountHistoryQuery) {
        this.AccountHistoryQuery=AccountHistoryQuery;
    }        
    private AccountHistory AccountHistory;
    
    public AccountHistory getAccountHistory() {
        return AccountHistory;
    }
    public void setAccountHistory(AccountHistory AccountHistory) {
        this.AccountHistory=AccountHistory;
    }        
    private ThirdPartyAuthorisationRuleSetList ThirdPartyAuthorisationRuleSetList;
    
    public ThirdPartyAuthorisationRuleSetList getThirdPartyAuthorisationRuleSetList() {
        return ThirdPartyAuthorisationRuleSetList;
    }
    public void setThirdPartyAuthorisationRuleSetList(ThirdPartyAuthorisationRuleSetList ThirdPartyAuthorisationRuleSetList) {
        this.ThirdPartyAuthorisationRuleSetList=ThirdPartyAuthorisationRuleSetList;
    }        
    private ProductSpecificationQuery ProductSpecificationQuery;
    
    public ProductSpecificationQuery getProductSpecificationQuery() {
        return ProductSpecificationQuery;
    }
    public void setProductSpecificationQuery(ProductSpecificationQuery ProductSpecificationQuery) {
        this.ProductSpecificationQuery=ProductSpecificationQuery;
    }        
    private ProductSpecificationList ProductSpecificationList;
    
    public ProductSpecificationList getProductSpecificationList() {
        return ProductSpecificationList;
    }
    public void setProductSpecificationList(ProductSpecificationList ProductSpecificationList) {
        this.ProductSpecificationList=ProductSpecificationList;
    }        
    private TTComment TTComment;
    
    public TTComment getTTComment() {
        return TTComment;
    }
    public void setTTComment(TTComment TTComment) {
        this.TTComment=TTComment;
    }        
    private VerifyDefacedCustomerRequest VerifyDefacedCustomerRequest;
    
    public VerifyDefacedCustomerRequest getVerifyDefacedCustomerRequest() {
        return VerifyDefacedCustomerRequest;
    }
    public void setVerifyDefacedCustomerRequest(VerifyDefacedCustomerRequest VerifyDefacedCustomerRequest) {
        this.VerifyDefacedCustomerRequest=VerifyDefacedCustomerRequest;
    }        
    private TransactionReversalData TransactionReversalData;
    
    public TransactionReversalData getTransactionReversalData() {
        return TransactionReversalData;
    }
    public void setTransactionReversalData(TransactionReversalData TransactionReversalData) {
        this.TransactionReversalData=TransactionReversalData;
    }        
    private OrganisationQuery OrganisationQuery;
    
    public OrganisationQuery getOrganisationQuery() {
        return OrganisationQuery;
    }
    public void setOrganisationQuery(OrganisationQuery OrganisationQuery) {
        this.OrganisationQuery=OrganisationQuery;
    }        
    private OrganisationList OrganisationList;
    
    public OrganisationList getOrganisationList() {
        return OrganisationList;
    }
    public void setOrganisationList(OrganisationList OrganisationList) {
        this.OrganisationList=OrganisationList;
    }        
    private EventQuery EventQuery;
    
    public EventQuery getEventQuery() {
        return EventQuery;
    }
    public void setEventQuery(EventQuery EventQuery) {
        this.EventQuery=EventQuery;
    }        
    private EventList EventList;
    
    public EventList getEventList() {
        return EventList;
    }
    public void setEventList(EventList EventList) {
        this.EventList=EventList;
    }        
    private SaleModificationData SaleModificationData;
    
    public SaleModificationData getSaleModificationData() {
        return SaleModificationData;
    }
    public void setSaleModificationData(SaleModificationData SaleModificationData) {
        this.SaleModificationData=SaleModificationData;
    }        
    private NewStickyNote NewStickyNote;
    
    public NewStickyNote getNewStickyNote() {
        return NewStickyNote;
    }
    public void setNewStickyNote(NewStickyNote NewStickyNote) {
        this.NewStickyNote=NewStickyNote;
    }        
    private PrepaidStripRedemptionData PrepaidStripRedemptionData;
    
    public PrepaidStripRedemptionData getPrepaidStripRedemptionData() {
        return PrepaidStripRedemptionData;
    }
    public void setPrepaidStripRedemptionData(PrepaidStripRedemptionData PrepaidStripRedemptionData) {
        this.PrepaidStripRedemptionData=PrepaidStripRedemptionData;
    }        
    private Event Event;
    
    public Event getEvent() {
        return Event;
    }
    public void setEvent(Event Event) {
        this.Event=Event;
    }        
    private SCAString SCAString;
    
    public SCAString getSCAString() {
        return SCAString;
    }
    public void setSCAString(SCAString SCAString) {
        this.SCAString=SCAString;
    }        
    private StickyNoteTypeList StickyNoteTypeList;
    
    public StickyNoteTypeList getStickyNoteTypeList() {
        return StickyNoteTypeList;
    }
    public void setStickyNoteTypeList(StickyNoteTypeList StickyNoteTypeList) {
        this.StickyNoteTypeList=StickyNoteTypeList;
    }        
    private Photograph Photograph;
    
    public Photograph getPhotograph() {
        return Photograph;
    }
    public void setPhotograph(Photograph Photograph) {
        this.Photograph=Photograph;
    }        
    private TTUser TTUser;
    
    public TTUser getTTUser() {
        return TTUser;
    }
    public void setTTUser(TTUser TTUser) {
        this.TTUser=TTUser;
    }        
    private TransferGraphQuery TransferGraphQuery;
    
    public TransferGraphQuery getTransferGraphQuery() {
        return TransferGraphQuery;
    }
    public void setTransferGraphQuery(TransferGraphQuery TransferGraphQuery) {
        this.TransferGraphQuery=TransferGraphQuery;
    }        
    private TransferGraph TransferGraph;
    
    public TransferGraph getTransferGraph() {
        return TransferGraph;
    }
    public void setTransferGraph(TransferGraph TransferGraph) {
        this.TransferGraph=TransferGraph;
    }        
    private BatchRequest BatchRequest;
    
    public BatchRequest getBatchRequest() {
        return BatchRequest;
    }
    public void setBatchRequest(BatchRequest BatchRequest) {
        this.BatchRequest=BatchRequest;
    }        
    private BalanceTransferData BalanceTransferData;
    
    public BalanceTransferData getBalanceTransferData() {
        return BalanceTransferData;
    }
    public void setBalanceTransferData(BalanceTransferData BalanceTransferData) {
        this.BalanceTransferData=BalanceTransferData;
    }        
    private DeregisterIMPUQuery DeregisterIMPUQuery;
    
    public DeregisterIMPUQuery getDeregisterIMPUQuery() {
        return DeregisterIMPUQuery;
    }
    public void setDeregisterIMPUQuery(DeregisterIMPUQuery DeregisterIMPUQuery) {
        this.DeregisterIMPUQuery=DeregisterIMPUQuery;
    }        
    private PlatformEndPointList PlatformEndPointList;
    
    public PlatformEndPointList getPlatformEndPointList() {
        return PlatformEndPointList;
    }
    public void setPlatformEndPointList(PlatformEndPointList PlatformEndPointList) {
        this.PlatformEndPointList=PlatformEndPointList;
    }        
    private PaymentNotificationData PaymentNotificationData;
    
    public PaymentNotificationData getPaymentNotificationData() {
        return PaymentNotificationData;
    }
    public void setPaymentNotificationData(PaymentNotificationData PaymentNotificationData) {
        this.PaymentNotificationData=PaymentNotificationData;
    }        
    private Resource Resource;
    
    public Resource getResource() {
        return Resource;
    }
    public void setResource(Resource Resource) {
        this.Resource=Resource;
    }        
    private UpSizeInventoryQuery UpSizeInventoryQuery;
    
    public UpSizeInventoryQuery getUpSizeInventoryQuery() {
        return UpSizeInventoryQuery;
    }
    public void setUpSizeInventoryQuery(UpSizeInventoryQuery UpSizeInventoryQuery) {
        this.UpSizeInventoryQuery=UpSizeInventoryQuery;
    }        
    private ContractQuery ContractQuery;
    
    public ContractQuery getContractQuery() {
        return ContractQuery;
    }
    public void setContractQuery(ContractQuery ContractQuery) {
        this.ContractQuery=ContractQuery;
    }        
    private ContractList ContractList;
    
    public ContractList getContractList() {
        return ContractList;
    }
    public void setContractList(ContractList ContractList) {
        this.ContractList=ContractList;
    }        
    private CustomerCommunicationData CustomerCommunicationData;
    
    public CustomerCommunicationData getCustomerCommunicationData() {
        return CustomerCommunicationData;
    }
    public void setCustomerCommunicationData(CustomerCommunicationData CustomerCommunicationData) {
        this.CustomerCommunicationData=CustomerCommunicationData;
    }        
    private IMEIStatusChangeGetinfoRequest IMEIStatusChangeGetinfoRequest;
    
    public IMEIStatusChangeGetinfoRequest getIMEIStatusChangeGetinfoRequest() {
        return IMEIStatusChangeGetinfoRequest;
    }
    public void setIMEIStatusChangeGetinfoRequest(IMEIStatusChangeGetinfoRequest IMEIStatusChangeGetinfoRequest) {
        this.IMEIStatusChangeGetinfoRequest=IMEIStatusChangeGetinfoRequest;
    }        
    private NumbersQuery NumbersQuery;
    
    public NumbersQuery getNumbersQuery() {
        return NumbersQuery;
    }
    public void setNumbersQuery(NumbersQuery NumbersQuery) {
        this.NumbersQuery=NumbersQuery;
    }        
    private NumberList NumberList;
    
    public NumberList getNumberList() {
        return NumberList;
    }
    public void setNumberList(NumberList NumberList) {
        this.NumberList=NumberList;
    }        
    private PurgeUserDataQuery PurgeUserDataQuery;
    
    public PurgeUserDataQuery getPurgeUserDataQuery() {
        return PurgeUserDataQuery;
    }
    public void setPurgeUserDataQuery(PurgeUserDataQuery PurgeUserDataQuery) {
        this.PurgeUserDataQuery=PurgeUserDataQuery;
    }        
    private SIMVerifyRequest SIMVerifyRequest;
    
    public SIMVerifyRequest getSIMVerifyRequest() {
        return SIMVerifyRequest;
    }
    public void setSIMVerifyRequest(SIMVerifyRequest SIMVerifyRequest) {
        this.SIMVerifyRequest=SIMVerifyRequest;
    }        
    private SIMVerifyResponse SIMVerifyResponse;
    
    public SIMVerifyResponse getSIMVerifyResponse() {
        return SIMVerifyResponse;
    }
    public void setSIMVerifyResponse(SIMVerifyResponse SIMVerifyResponse) {
        this.SIMVerifyResponse=SIMVerifyResponse;
    }        
    private GeneralQueryRequest GeneralQueryRequest;
    
    public GeneralQueryRequest getGeneralQueryRequest() {
        return GeneralQueryRequest;
    }
    public void setGeneralQueryRequest(GeneralQueryRequest GeneralQueryRequest) {
        this.GeneralQueryRequest=GeneralQueryRequest;
    }        
    private GeneralQueryResponse GeneralQueryResponse;
    
    public GeneralQueryResponse getGeneralQueryResponse() {
        return GeneralQueryResponse;
    }
    public void setGeneralQueryResponse(GeneralQueryResponse GeneralQueryResponse) {
        this.GeneralQueryResponse=GeneralQueryResponse;
    }        
    private ServiceActivationData ServiceActivationData;
    
    public ServiceActivationData getServiceActivationData() {
        return ServiceActivationData;
    }
    public void setServiceActivationData(ServiceActivationData ServiceActivationData) {
        this.ServiceActivationData=ServiceActivationData;
    }        
    private TTJiraUserQuery TTJiraUserQuery;
    
    public TTJiraUserQuery getTTJiraUserQuery() {
        return TTJiraUserQuery;
    }
    public void setTTJiraUserQuery(TTJiraUserQuery TTJiraUserQuery) {
        this.TTJiraUserQuery=TTJiraUserQuery;
    }        
    private TTJiraUserList TTJiraUserList;
    
    public TTJiraUserList getTTJiraUserList() {
        return TTJiraUserList;
    }
    public void setTTJiraUserList(TTJiraUserList TTJiraUserList) {
        this.TTJiraUserList=TTJiraUserList;
    }        
    private ResourceList ResourceList;
    
    public ResourceList getResourceList() {
        return ResourceList;
    }
    public void setResourceList(ResourceList ResourceList) {
        this.ResourceList=ResourceList;
    }        
    private ReturnData ReturnData;
    
    public ReturnData getReturnData() {
        return ReturnData;
    }
    public void setReturnData(ReturnData ReturnData) {
        this.ReturnData=ReturnData;
    }        
    private CreditNote CreditNote;
    
    public CreditNote getCreditNote() {
        return CreditNote;
    }
    public void setCreditNote(CreditNote CreditNote) {
        this.CreditNote=CreditNote;
    }        
    private ProductOrder ProductOrder;
    
    public ProductOrder getProductOrder() {
        return ProductOrder;
    }
    public void setProductOrder(ProductOrder ProductOrder) {
        this.ProductOrder=ProductOrder;
    }        
    private SoldStockLocationQuery SoldStockLocationQuery;
    
    public SoldStockLocationQuery getSoldStockLocationQuery() {
        return SoldStockLocationQuery;
    }
    public void setSoldStockLocationQuery(SoldStockLocationQuery SoldStockLocationQuery) {
        this.SoldStockLocationQuery=SoldStockLocationQuery;
    }        
    private SoldStockLocationList SoldStockLocationList;
    
    public SoldStockLocationList getSoldStockLocationList() {
        return SoldStockLocationList;
    }
    public void setSoldStockLocationList(SoldStockLocationList SoldStockLocationList) {
        this.SoldStockLocationList=SoldStockLocationList;
    }        
    private NewSIMCardData NewSIMCardData;
    
    public NewSIMCardData getNewSIMCardData() {
        return NewSIMCardData;
    }
    public void setNewSIMCardData(NewSIMCardData NewSIMCardData) {
        this.NewSIMCardData=NewSIMCardData;
    }        
    private SIMSwapRequest SIMSwapRequest;
    
    public SIMSwapRequest getSIMSwapRequest() {
        return SIMSwapRequest;
    }
    public void setSIMSwapRequest(SIMSwapRequest SIMSwapRequest) {
        this.SIMSwapRequest=SIMSwapRequest;
    }        
    private PurchaseUnitCreditRequest PurchaseUnitCreditRequest;
    
    public PurchaseUnitCreditRequest getPurchaseUnitCreditRequest() {
        return PurchaseUnitCreditRequest;
    }
    public void setPurchaseUnitCreditRequest(PurchaseUnitCreditRequest PurchaseUnitCreditRequest) {
        this.PurchaseUnitCreditRequest=PurchaseUnitCreditRequest;
    }        
    private SalesQuery SalesQuery;
    
    public SalesQuery getSalesQuery() {
        return SalesQuery;
    }
    public void setSalesQuery(SalesQuery SalesQuery) {
        this.SalesQuery=SalesQuery;
    }        
    private SalesList SalesList;
    
    public SalesList getSalesList() {
        return SalesList;
    }
    public void setSalesList(SalesList SalesList) {
        this.SalesList=SalesList;
    }        
    private SSOPasswordResetData SSOPasswordResetData;
    
    public SSOPasswordResetData getSSOPasswordResetData() {
        return SSOPasswordResetData;
    }
    public void setSSOPasswordResetData(SSOPasswordResetData SSOPasswordResetData) {
        this.SSOPasswordResetData=SSOPasswordResetData;
    }        
    private AuthenticationQuery AuthenticationQuery;
    
    public AuthenticationQuery getAuthenticationQuery() {
        return AuthenticationQuery;
    }
    public void setAuthenticationQuery(AuthenticationQuery AuthenticationQuery) {
        this.AuthenticationQuery=AuthenticationQuery;
    }        
    private AuthenticationResult AuthenticationResult;
    
    public AuthenticationResult getAuthenticationResult() {
        return AuthenticationResult;
    }
    public void setAuthenticationResult(AuthenticationResult AuthenticationResult) {
        this.AuthenticationResult=AuthenticationResult;
    }        
    private NAIIdentityQuery NAIIdentityQuery;
    
    public NAIIdentityQuery getNAIIdentityQuery() {
        return NAIIdentityQuery;
    }
    public void setNAIIdentityQuery(NAIIdentityQuery NAIIdentityQuery) {
        this.NAIIdentityQuery=NAIIdentityQuery;
    }        
    private NAIIdentity NAIIdentity;
    
    public NAIIdentity getNAIIdentity() {
        return NAIIdentity;
    }
    public void setNAIIdentity(NAIIdentity NAIIdentity) {
        this.NAIIdentity=NAIIdentity;
    }        
    private ReverseGLData ReverseGLData;
    
    public ReverseGLData getReverseGLData() {
        return ReverseGLData;
    }
    public void setReverseGLData(ReverseGLData ReverseGLData) {
        this.ReverseGLData=ReverseGLData;
    }        
    private ReverseGLOut ReverseGLOut;
    
    public ReverseGLOut getReverseGLOut() {
        return ReverseGLOut;
    }
    public void setReverseGLOut(ReverseGLOut ReverseGLOut) {
        this.ReverseGLOut=ReverseGLOut;
    }        
    private UnitCreditInstance UnitCreditInstance;
    
    public UnitCreditInstance getUnitCreditInstance() {
        return UnitCreditInstance;
    }
    public void setUnitCreditInstance(UnitCreditInstance UnitCreditInstance) {
        this.UnitCreditInstance=UnitCreditInstance;
    }        
    private PrepaidStripQuery PrepaidStripQuery;
    
    public PrepaidStripQuery getPrepaidStripQuery() {
        return PrepaidStripQuery;
    }
    public void setPrepaidStripQuery(PrepaidStripQuery PrepaidStripQuery) {
        this.PrepaidStripQuery=PrepaidStripQuery;
    }        
    private PrepaidStrip PrepaidStrip;
    
    public PrepaidStrip getPrepaidStrip() {
        return PrepaidStrip;
    }
    public void setPrepaidStrip(PrepaidStrip PrepaidStrip) {
        this.PrepaidStrip=PrepaidStrip;
    }        
    private CreateStandardGLData CreateStandardGLData;
    
    public CreateStandardGLData getCreateStandardGLData() {
        return CreateStandardGLData;
    }
    public void setCreateStandardGLData(CreateStandardGLData CreateStandardGLData) {
        this.CreateStandardGLData=CreateStandardGLData;
    }        
    private CreateStandardGLOut CreateStandardGLOut;
    
    public CreateStandardGLOut getCreateStandardGLOut() {
        return CreateStandardGLOut;
    }
    public void setCreateStandardGLOut(CreateStandardGLOut CreateStandardGLOut) {
        this.CreateStandardGLOut=CreateStandardGLOut;
    }        
    private StickyNoteType StickyNoteType;
    
    public StickyNoteType getStickyNoteType() {
        return StickyNoteType;
    }
    public void setStickyNoteType(StickyNoteType StickyNoteType) {
        this.StickyNoteType=StickyNoteType;
    }        
    private ShortMessage ShortMessage;
    
    public ShortMessage getShortMessage() {
        return ShortMessage;
    }
    public void setShortMessage(ShortMessage ShortMessage) {
        this.ShortMessage=ShortMessage;
    }        
    private TNFQuery TNFQuery;
    
    public TNFQuery getTNFQuery() {
        return TNFQuery;
    }
    public void setTNFQuery(TNFQuery TNFQuery) {
        this.TNFQuery=TNFQuery;
    }        
    private TNFData TNFData;
    
    public TNFData getTNFData() {
        return TNFData;
    }
    public void setTNFData(TNFData TNFData) {
        this.TNFData=TNFData;
    }        
    private SalePostProcessingData SalePostProcessingData;
    
    public SalePostProcessingData getSalePostProcessingData() {
        return SalePostProcessingData;
    }
    public void setSalePostProcessingData(SalePostProcessingData SalePostProcessingData) {
        this.SalePostProcessingData=SalePostProcessingData;
    }        
    private AccountSummaryQuery AccountSummaryQuery;
    
    public AccountSummaryQuery getAccountSummaryQuery() {
        return AccountSummaryQuery;
    }
    public void setAccountSummaryQuery(AccountSummaryQuery AccountSummaryQuery) {
        this.AccountSummaryQuery=AccountSummaryQuery;
    }        
    private AccountSummary AccountSummary;
    
    public AccountSummary getAccountSummary() {
        return AccountSummary;
    }
    public void setAccountSummary(AccountSummary AccountSummary) {
        this.AccountSummary=AccountSummary;
    }        
    private CampaignData CampaignData;
    
    public CampaignData getCampaignData() {
        return CampaignData;
    }
    public void setCampaignData(CampaignData CampaignData) {
        this.CampaignData=CampaignData;
    }        
    private ScheduledAccountHistory ScheduledAccountHistory;
    
    public ScheduledAccountHistory getScheduledAccountHistory() {
        return ScheduledAccountHistory;
    }
    public void setScheduledAccountHistory(ScheduledAccountHistory ScheduledAccountHistory) {
        this.ScheduledAccountHistory=ScheduledAccountHistory;
    }        
    private BatchScheduleList BatchScheduleList;
    
    public BatchScheduleList getBatchScheduleList() {
        return BatchScheduleList;
    }
    public void setBatchScheduleList(BatchScheduleList BatchScheduleList) {
        this.BatchScheduleList=BatchScheduleList;
    }        
    private UserIDToCheck UserIDToCheck;
    
    public UserIDToCheck getUserIDToCheck() {
        return UserIDToCheck;
    }
    public void setUserIDToCheck(UserIDToCheck UserIDToCheck) {
        this.UserIDToCheck=UserIDToCheck;
    }        
    private TTCheck TTCheck;
    
    public TTCheck getTTCheck() {
        return TTCheck;
    }
    public void setTTCheck(TTCheck TTCheck) {
        this.TTCheck=TTCheck;
    }        
    private CashInData CashInData;
    
    public CashInData getCashInData() {
        return CashInData;
    }
    public void setCashInData(CashInData CashInData) {
        this.CashInData=CashInData;
    }        
    private TTMetaDataQuery TTMetaDataQuery;
    
    public TTMetaDataQuery getTTMetaDataQuery() {
        return TTMetaDataQuery;
    }
    public void setTTMetaDataQuery(TTMetaDataQuery TTMetaDataQuery) {
        this.TTMetaDataQuery=TTMetaDataQuery;
    }        
    private TTMetaData TTMetaData;
    
    public TTMetaData getTTMetaData() {
        return TTMetaData;
    }
    public void setTTMetaData(TTMetaData TTMetaData) {
        this.TTMetaData=TTMetaData;
    }        
    private TTIssueQuery TTIssueQuery;
    
    public TTIssueQuery getTTIssueQuery() {
        return TTIssueQuery;
    }
    public void setTTIssueQuery(TTIssueQuery TTIssueQuery) {
        this.TTIssueQuery=TTIssueQuery;
    }        
    private TTIssueList TTIssueList;
    
    public TTIssueList getTTIssueList() {
        return TTIssueList;
    }
    public void setTTIssueList(TTIssueList TTIssueList) {
        this.TTIssueList=TTIssueList;
    }        
    private IMSSubscriptionStatusUpdateData IMSSubscriptionStatusUpdateData;
    
    public IMSSubscriptionStatusUpdateData getIMSSubscriptionStatusUpdateData() {
        return IMSSubscriptionStatusUpdateData;
    }
    public void setIMSSubscriptionStatusUpdateData(IMSSubscriptionStatusUpdateData IMSSubscriptionStatusUpdateData) {
        this.IMSSubscriptionStatusUpdateData=IMSSubscriptionStatusUpdateData;
    }        
    private IMEICheckRequest IMEICheckRequest;
    
    public IMEICheckRequest getIMEICheckRequest() {
        return IMEICheckRequest;
    }
    public void setIMEICheckRequest(IMEICheckRequest IMEICheckRequest) {
        this.IMEICheckRequest=IMEICheckRequest;
    }        
    private IMEICheckResponse IMEICheckResponse;
    
    public IMEICheckResponse getIMEICheckResponse() {
        return IMEICheckResponse;
    }
    public void setIMEICheckResponse(IMEICheckResponse IMEICheckResponse) {
        this.IMEICheckResponse=IMEICheckResponse;
    }        
    private CustomerQuery CustomerQuery;
    
    public CustomerQuery getCustomerQuery() {
        return CustomerQuery;
    }
    public void setCustomerQuery(CustomerQuery CustomerQuery) {
        this.CustomerQuery=CustomerQuery;
    }        
    private CustomerList CustomerList;
    
    public CustomerList getCustomerList() {
        return CustomerList;
    }
    public void setCustomerList(CustomerList CustomerList) {
        this.CustomerList=CustomerList;
    }        
    private SCSCFIMPUQuery SCSCFIMPUQuery;
    
    public SCSCFIMPUQuery getSCSCFIMPUQuery() {
        return SCSCFIMPUQuery;
    }
    public void setSCSCFIMPUQuery(SCSCFIMPUQuery SCSCFIMPUQuery) {
        this.SCSCFIMPUQuery=SCSCFIMPUQuery;
    }        
    private SCSCFIMPUData SCSCFIMPUData;
    
    public SCSCFIMPUData getSCSCFIMPUData() {
        return SCSCFIMPUData;
    }
    public void setSCSCFIMPUData(SCSCFIMPUData SCSCFIMPUData) {
        this.SCSCFIMPUData=SCSCFIMPUData;
    }        
    private SCADateTime SCADateTime;
    
    public SCADateTime getSCADateTime() {
        return SCADateTime;
    }
    public void setSCADateTime(SCADateTime SCADateTime) {
        this.SCADateTime=SCADateTime;
    }        
    private String String;
    
    public String getString() {
        return String;
    }
    public void setString(String String) {
        this.String=String;
    }        
    private Return Return;
    
    public Return getReturn() {
        return Return;
    }
    public void setReturn(Return Return) {
        this.Return=Return;
    }        
    private NewPrepaidStripsData NewPrepaidStripsData;
    
    public NewPrepaidStripsData getNewPrepaidStripsData() {
        return NewPrepaidStripsData;
    }
    public void setNewPrepaidStripsData(NewPrepaidStripsData NewPrepaidStripsData) {
        this.NewPrepaidStripsData=NewPrepaidStripsData;
    }        
    private PrepaidStrips PrepaidStrips;
    
    public PrepaidStrips getPrepaidStrips() {
        return PrepaidStrips;
    }
    public void setPrepaidStrips(PrepaidStrips PrepaidStrips) {
        this.PrepaidStrips=PrepaidStrips;
    }        
    private PortInEvent PortInEvent;
    
    public PortInEvent getPortInEvent() {
        return PortInEvent;
    }
    public void setPortInEvent(PortInEvent PortInEvent) {
        this.PortInEvent=PortInEvent;
    }        
    private SCALong SCALong;
    
    public SCALong getSCALong() {
        return SCALong;
    }
    public void setSCALong(SCALong SCALong) {
        this.SCALong=SCALong;
    }        
    private ServiceInstanceQuery ServiceInstanceQuery;
    
    public ServiceInstanceQuery getServiceInstanceQuery() {
        return ServiceInstanceQuery;
    }
    public void setServiceInstanceQuery(ServiceInstanceQuery ServiceInstanceQuery) {
        this.ServiceInstanceQuery=ServiceInstanceQuery;
    }        
    private ServiceInstanceList ServiceInstanceList;
    
    public ServiceInstanceList getServiceInstanceList() {
        return ServiceInstanceList;
    }
    public void setServiceInstanceList(ServiceInstanceList ServiceInstanceList) {
        this.ServiceInstanceList=ServiceInstanceList;
    }        
    private AccountQuery AccountQuery;
    
    public AccountQuery getAccountQuery() {
        return AccountQuery;
    }
    public void setAccountQuery(AccountQuery AccountQuery) {
        this.AccountQuery=AccountQuery;
    }        
    private AccountList AccountList;
    
    public AccountList getAccountList() {
        return AccountList;
    }
    public void setAccountList(AccountList AccountList) {
        this.AccountList=AccountList;
    }        
    private SoldStockLocationData SoldStockLocationData;
    
    public SoldStockLocationData getSoldStockLocationData() {
        return SoldStockLocationData;
    }
    public void setSoldStockLocationData(SoldStockLocationData SoldStockLocationData) {
        this.SoldStockLocationData=SoldStockLocationData;
    }        
    private VoucherLockForAccountQuery VoucherLockForAccountQuery;
    
    public VoucherLockForAccountQuery getVoucherLockForAccountQuery() {
        return VoucherLockForAccountQuery;
    }
    public void setVoucherLockForAccountQuery(VoucherLockForAccountQuery VoucherLockForAccountQuery) {
        this.VoucherLockForAccountQuery=VoucherLockForAccountQuery;
    }        
    private VoucherLockForAccount VoucherLockForAccount;
    
    public VoucherLockForAccount getVoucherLockForAccount() {
        return VoucherLockForAccount;
    }
    public void setVoucherLockForAccount(VoucherLockForAccount VoucherLockForAccount) {
        this.VoucherLockForAccount=VoucherLockForAccount;
    }        
    private ServiceSpecificationQuery ServiceSpecificationQuery;
    
    public ServiceSpecificationQuery getServiceSpecificationQuery() {
        return ServiceSpecificationQuery;
    }
    public void setServiceSpecificationQuery(ServiceSpecificationQuery ServiceSpecificationQuery) {
        this.ServiceSpecificationQuery=ServiceSpecificationQuery;
    }        
    private ServiceSpecification ServiceSpecification;
    
    public ServiceSpecification getServiceSpecification() {
        return ServiceSpecification;
    }
    public void setServiceSpecification(ServiceSpecification ServiceSpecification) {
        this.ServiceSpecification=ServiceSpecification;
    }        
    
        
} 
 
    